### ISSUE TITLE
Navbar készítése

### ISSUE THREAD

**Issue by Atrombix** [czafikm/AFP-Team-6#21]
Készítsetek egy alap navbart a projecthez, valamint egy kicsit design-oljátok ki a frontendet.

**AC:**
-Navbaron szerepeljen (Project neve mint Navbar-brand, Guest Add,Guest List,Add Watch,List Watch)
-Listázás egy táblázatban történjen.
-Hozzáadás form egy Card legyen (Az enum értékek egy legördülő lista legyen).

**Comment by VLGJBZ** [comment]
Design és a navbar elkészítése  sikeres volt.
